name: Build

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.5.0
        with:
          java-version: 13
      - run: |
          curl -L https://github.com/flix/flix/releases/latest/download/flix.jar > flix.jar
          alias flix=java -jar flix.jar
          flix test
